### ISSUE TITLE
Add guide on how to set up your own Web3 gateway for Emerald/Sapphire

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/docs#249]
We need an end-to-end guide that will help dApp developer/operators understand and set up their own Web3 gateway for Emerald or Sapphire.

The guide should include sections on how to:
1. Set up a full consensus node (what we usually call a non-validator node)
2. Set up a ParaTime client node
3. Set up a Web3 gateway that connects to Oasis node that is set up be a ParaTime client node

The guide could also summarize the general hardware requirements and prerequisites (PostgreSQL database).

**Comment by matevz** [comment]
Implemented in https://github.com/oasisprotocol/docs/pull/250
