### ISSUE TITLE
Fix routing from inner pages after refresh

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#4]
1. Visit https://docs.oasis.dev/general/oasis-network/network-parameters/
2. Scroll down to Testnet link
3. Click on the link.
4.  => Results in 404 page not found because it's linking (with javascript routes window.href=...) to https://docs.oasis.dev/general/oasis-network/foundation/testnet/ (notice the redundant `/oasis-network/` chunk)

This only happens when initially visiting the URL of an internal page and then navigating from there. If you commence with the landing page and then navigating through the page, you will not encounter this. Also, oasis-core and oasis-sdk are not affected by this. Also, disabling javascript fixes the issue.

Maybe check how docusaurus.io website handles this as they also use multi-sites.

**Comment by lukaw3d** [comment]
Seems to be because of `trailingSlash`. There are a lot of issues about it, e.g. https://github.com/facebook/docusaurus/issues/5250

**Comment by matevz** [comment]
> Seems to be because of `trailingSlash`. There are a lot of issues about it, e.g. [facebook/docusaurus#5250](https://github.com/facebook/docusaurus/issues/5250)

Yeah, I tried disabling or enabling `trailingSlash`, but that caused a handful of other links to break and pages not being compiled across the app :/

**Comment by lukaw3d** [comment]
Hm, it looks like this fixes it
```diff
- [Testnet](../foundation/testnet/)
+ [Testnet](../foundation/testnet/README.md)
```

Related docs https://docusaurus.io/docs/versioning#link-docs-by-file-paths

**Comment by lukaw3d** [comment]
I checked that it works locally, in both
- `http://localhost:3000/general/oasis-network/network-parameters`
- `http://localhost:3000/general/oasis-network/network-parameters/`

same with
```diff
- [run your own](../run-a-node/set-up-your-node/run-an-ias-proxy)
+ [run your own](../run-a-node/set-up-your-node/run-an-ias-proxy.md)
```
