### ISSUE TITLE
Ideas for potential changes

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/docs#53]
**Ideas**

These (all optional/maybe nice-to-haves) pertain to the new [Emerald docs](https://docs.oasis.dev/general/developer-resources/emerald-paratime/writing-dapps-on-emerald).

1. I think [this](https://github.com/oasisprotocol/docs/blob/2f78e149a7a003aa461cd3397523887f4852ddac/docs/general/developer-resources/emerald-paratime/writing-dapps-on-emerald.md?plain=1#L179) already suggests that Hardhat download is slow, but I originally was wondering if we want to warn devs about that more explicitly.
2. My Truffle installations had a lot of warnings. Maybe we want to warn about that.
3. When tested previously (> 30 days ago), my Truffle setup encountered timeout, and nonce issues, but I believe it did succeed.
4. We go over Truffle, Hardhat, and Remix all on one page. I think this makes searching very easy, but does mean we have a mega page of information. Maybe there is a way to break this up.
5. Perhaps we could resize some of the screenshots in the ROSE [transfer page](https://docs.oasis.dev/general/manage-tokens/how-to-transfer-rose-into-emerald-paratime).
6. web3.js [link](https://github.com/oasisprotocol/docs/blob/2f78e149a7a003aa461cd3397523887f4852ddac/docs/general/developer-resources/emerald-paratime/writing-dapps-on-emerald.md?plain=1#L565) is pinned to a version

**Comment by matevz** [comment]
All suggestions above have been addressed a while ago. Closing.
