### ISSUE TITLE
Move generals docs to top-level and add redirect

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/docs#8]
When we had GitBook-powered Oasis Docs, their setup required redirecting `https//docs.oasis.dev/<URL>` to `https://docs.oasis.dev/general/<URL>`.

Can we get rid of that and enable shorter URLs by:
- Moving `docs/general/*` to `docs/`
- Creating the opposite redirects from `https://docs.oasis.dev/general/<URL>` to `https//docs.oasis.dev/<URL>` for compatibility?

**Comment by matevz** [comment]
Superseeded by #125 and #184.
