### ISSUE TITLE
Document Sapphire and Remix

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#866]
See what is needed for Remix to work seamlessly with Sapphire. Currently, it only works via "universal" metamask connector. A section on this was written [years ago for Emerald](https://docs.oasis.io/dapp/emerald/writing-dapps-on-emerald#create-dapp-on-emerald-with-remix---ethereum-ide). Revamp it for Sapphire and move it out of Emerald into a separate chapter under https://docs.oasis.io/dapp/tools/ ➝ Remix.

OFC you won't be able to debug in Remix much against Sapphire because it won't reveal confidential information.

Don't forget to mention the transactions and queries are unencrypted and unsigned.

Don't forget to pinpoint solc version up to 0.8.24 (see https://github.com/rust-ethereum/evm/issues/277).

Also consider, if the Explorer➝Sourcify➝Remix flow is feasible to interact with a smart contract and worth describing it in this chapter how a (non-tech) user could communicate with the smart contract, e.g. if the maintainer decides to shut down the dApp frontend and the user is stuck with the contract and wants to withdraw his assets back.  FYI @lukaw3d built a simpler alternative https://abi-playground.oasis.io/ for this.

**Comment by lukaw3d** [comment]
Maybe we can edit remix to allow sapphire in walletconnect 
![image](https://github.com/user-attachments/assets/b6afefe7-06b4-4011-a158-71c3b117830b)

**Comment by lukaw3d** [comment]
https://github.com/ethereum/remix-project/blob/7211c686f4fd45687858d67fe5a70ce787d5e56e/apps/remix-dapp/src/utils/walletConnect.ts#L34  -> https://github.com/ethereum/remix-project/blob/7211c686f4fd45687858d67fe5a70ce787d5e56e/apps/remix-dapp/src/utils/constants.ts#L23-L45

https://github.com/ethereum/remix-project/blob/7211c686f4fd45687858d67fe5a70ce787d5e56e/apps/walletconnect/src/services/WalletConnectRemixClient.ts#L45 -> https://github.com/ethereum/remix-project/blob/7211c686f4fd45687858d67fe5a70ce787d5e56e/apps/walletconnect/src/utils/chains.ts#L1

**Comment by lukaw3d** [comment]
Reproducing an already verified contract annoyances:
https://explorer.oasis.io/mainnet/sapphire/address/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3
- Open in Sourcify
- View in Remix
- https://remix.ethereum.org/?#activate=sourcify&call=sourcify//fetchAndSave//0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3//23294
- UI shows Solidity Compiler: 0.8.26 (probably kept selection from before)
  even though cloned metadata.json specified `"version": "0.8.16+commit.07a7930e"`
- Open WrappedROSE at path `verified-sources/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3/sources/contracts/WrappedROSE.sol`
- Click compile. The resulting bytecode is different!
- WrappedROSE imports `@openzeppelin/contracts/token/ERC20/ERC20.sol`, and verified correct version of this dependency was cloned into `verified-sources/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3/sources/@openzeppelin/contracts/token/ERC20/ERC20.sol`
  file starts with
  > `// OpenZeppelin Contracts (last updated v4.7.0) (token/ERC20/ERC20.sol)`
- But Remix automatically downloaded latest dependency into `.deps/npm/@openzeppelin/contracts/token/ERC20/ERC20.sol`
  > `// OpenZeppelin Contracts (last updated v5.0.0) (token/ERC20/ERC20.sol)`
  and compiled using this instead
- To reproduce the original bytecode, manually switch compiler version `0.8.16`. Adjust advanced config to match metadata.json `"optimizer": { "enabled": true, "runs": 0 }`
- Remix now marks modern ERC20.sol as incompatible with compiler. Delete `.deps/npm/@openzeppelin/contracts` and move `verified-sources/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3/sources/@openzeppelin/contracts` there.
- Recompile
- still "The deployed and recompiled bytecode don't match."

:shrug:

**Comment by rube-de** [comment]
> Maybe we can edit remix to allow sapphire in walletconnect ![image](https://private-user-images.githubusercontent.com/3758846/371695162-b6afefe7-06b4-4011-a158-71c3b117830b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTIyNDUsIm5iZiI6MTczMDExMTk0NSwicGF0aCI6Ii8zNzU4ODQ2LzM3MTY5NTE2Mi1iNmFmZWZlNy0wNmI0LTQwMTEtYTE1OC03MWMzYjExNzgzMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTAzOTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI3NjZjODM3OGY5NjZmMjg5ODdkNWE5NWM4ZDkyZDkyOTUxM2Y4YzczY2RlYjcyODlmNDQxMjBkYTM2ZGJkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lVT6Vd4bJnGxz6IvilD_B_QsslVAIJh7eWMfSXbAX5A)

IMHO that's low prio. I never noticed that's possible before 😅 and can't remember a tutorial that used WalletConnect in Remix. I could see to use it to deploy via ledger if you want to do it directly with Ledger live, but you could also deploy with Ledger via MetaMask.

**Comment by rube-de** [comment]
> Reproducing an already verified contract annoyances: https://explorer.oasis.io/mainnet/sapphire/address/0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3
> 
> * Open in Sourcify
> * View in Remix
> * https://remix.ethereum.org/?#activate=sourcify&call=sourcify//fetchAndSave//0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3//23294

Open in Remix from sourcify just opens the default workspace in Remix

opened an issue on their side https://github.com/ethereum/sourcify/issues/1730

**Comment by rube-de** [comment]
I think ABI Playground should be separate chapter 
opened an issue for this https://github.com/oasisprotocol/docs/issues/1012
