### ISSUE TITLE
Revamp OPL docs: OPL vs Celer IM vs Router Protocol

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/docs#929]
Currently it's heavily focused on OPL, our wrapper for CelerIM

But with [Router Protocol](https://www.routerprotocol.com/) now  supporting Oasis Sapphire, and many people needing to use Celer IM SDK directly for situations where the simple OPL wrapper isn't sufficient, we should expand the documentation to cover OPL at a higher level with 3 different approaches:

 1. Use the simplified OPL SDK (which uses Celer IM behind the scenes)
 2. Use the Celer SDK directly (for hub/spoke patterns, sending tokens along with messages, rejections etc.)
 3. Use Router Protocol

**Comment by rube-de** [comment]
https://github.com/oasisprotocol/docs/pull/974 add new Router Protocol section
