### ISSUE TITLE
Fix staking requirements page

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#946]
Update the [staking requirements](https://docs.oasis.io/node/run-your-node/prerequisites/stake-requirements) page:
- copy the requirements to the Testnet section too
- add minimum stake to run Sapphire and Emerald ParaTime compute node: 50k for Maninet, 100 for Testnet
- add minimum stake to run Ciphre ParaTime compute node: 100 for Maninet, 100 for Testnet

**Comment by rube-de** [comment]
>     * copy the requirements to the Testnet section too
I assume just the registration requirements, as it's far from the top120 limit in on the testnet? Or is there another limit on the testnet?
