### ISSUE TITLE
SGX Compatible Cloud / Bare-metal providers

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/docs#957]
We need to keep a list of cloud providers which are known to work (or, should work) with SGX, for third-parties to deploy various Oasis related projects on.

Currently:

 * OVH support SGX on their bare-metal servers: https://www.ovhcloud.com/en/bare-metal/prices/?use_cases=confidential-computing
 * Azure support SGX: https://learn.microsoft.com/en-us/azure/confidential-computing/virtual-machine-solutions-sgx for their DCsv2, DCsv3, and DCdsv3 VMs
 * GCore support SGX in some locations: https://gcore.com/cloud/intel-sgx
 * PhoenixNAP support SGX: https://phoenixnap.com/kb/intel-sgx
 * Alibaba cloud: https://www.alibabacloud.com/en/product/ebm?_p_lc=1
 * IBM Cloud: https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers-with-sgx-vpc
 * Vultr bare-metal: https://www.vultr.com/products/bare-metal/

The list should provide last-updated time, and also solicit recommendations

**Comment by gw0** [comment]
@amela Are we certain that Oasis-node with confidential ParaTimes can run on all of these providers?

**Comment by kostko** [comment]
I don't see why not as long as all the BIOS updates have been applied.
