### ISSUE TITLE
Move the Localnet docker section into separate chapter

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#959]
Similarly to how we moved the network settings to a separate chapter and how we revamped the Band protocol ([#907](https://github.com/oasisprotocol/docs/pull/907)), I suggest we devote a new "Localnet Development" (`dapp/tools/localnet.md`) chapter which includes the current content of https://docs.oasis.io/dapp/sapphire/guide#running-a-private-oasis-network-locally

TODO:
- [x] mention it could also be used for running Emerald (and replace https://docs.oasis.io/dapp/emerald/writing-dapps-on-emerald#running-a-private-oasis-network-locally with a link to the new chapter)
- [x] mention it in the ROFL chapter: https://docs.oasis.io/rofl/app#testing-it-on-sapphire-localnet
- [x] replace any links throughout the docs pointing to Sapphire Guide subsection or any links pointing directly to https://github.com/oasisprotocol/oasis-web3-gateway/pkgs/container/sapphire-localnet or https://github.com/oasisprotocol/oasis-web3-gateway/tree/main/docker with the new https://docs.oasis.io/dapp/tools/localnet
- [x] mention that minimum requirements for running the Sapphire Localnet image (at least 16GB of memory)

**Comment by aefhm** [comment]
Merge sequence:

- [x] New page goes in first https://github.com/oasisprotocol/docs/pull/977
- [x] Dependent reference https://github.com/oasisprotocol/cli/pull/310
- [x] Dependent reference https://github.com/oasisprotocol/sapphire-paratime/pull/429
- [x] Dependent reference https://github.com/oasisprotocol/oasis-sdk/pull/2023
- [x] Bump `sapphire-paratime`, `oasis-sdk`, and `oasis-cli` submodules to publish
