### ISSUE TITLE
Remove Goerli and Mumbai testnet references

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/docs#962]
## Description

Remove dead links.

**Comment by rube-de** [comment]
While I agree to remove old testnets, is cbridge supporting any other tokens from other testnets, like holesky?

**Comment by aefhm** [comment]
> While I agree to remove old testnets, is cbridge supporting any other tokens from other testnets, like holesky?

Looking at the testnet config from their [endpoint](https://cbridge-v2-test.celer.network/v1/getTransferConfigs), I don't see any deployed pairs there. Maybe they intend to do so in the future?
